config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "home#index"
  get "home/index"
  resources :movies
  resources :cines
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cine.rb
class Cine < ApplicationRecord
  has_many :movie
  mount_uploader :picture, PictureUploader
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :cine
  mount_uploader :picture, PictureUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cines_controller.rb
class CinesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_cine, only: [:show, :edit, :update, :destroy]

  # GET /cines
  # GET /cines.json
  def index
    @cines = Cine.all
  end

  # GET /cines/1
  # GET /cines/1.json
  def show
  end

  # GET /cines/new
  def new
    @cine = Cine.new
  end

  # GET /cines/1/edit
  def edit
  end

  # POST /cines
  # POST /cines.json
  def create
    @cine = Cine.new(cine_params)

    respond_to do |format|
      if @cine.save
        format.html { redirect_to @cine, notice: "Cine fue creado con éxito." }
        format.json { render :show, status: :created, location: @cine }
      else
        format.html { render :new }
        format.json { render json: @cine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cines/1
  # PATCH/PUT /cines/1.json
  def update
    respond_to do |format|
      if @cine.update(cine_params)
        format.html { redirect_to @cine, notice: " Cine se actualizó con éxito." }
        format.json { render :show, status: :ok, location: @cine }
      else
        format.html { render :edit }
        format.json { render json: @cine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cines/1
  # DELETE /cines/1.json
  def destroy
    @cine.destroy
    respond_to do |format|
      format.html { redirect_to cines_url, notice: " Cine fue eliminado con éxito." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_cine
    @cine = Cine.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def cine_params
    params.require(:cine).permit :name, :phone, :picture
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  #before_action :authenticate_user!
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  def index
    @movies = Movie.joins(:cine).all
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.joins(:cine).all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
    @cine = Cine.all.collect { |u| [u.name, u.id] }
  end

  # GET /movies/1/edit
  def edit
    @cine = Cine.all.collect { |u| [u.name, u.id] }
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: " La película se creó con éxito." }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: "La película se actualizó correctamente." }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: "La película fue eliminada con éxito." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_movie
    @movie = Movie.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def movie_params
    params.require(:movie).permit :name, :duration, :date_time_movie, :cine_id, :picture
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cines_helper.rb
module CinesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/cines/_form.html.erb
<%= form_with(model: cine, local: true) do |form| %>
  <% if cine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cine.errors.count, "error") %> prohibited this cine from being saved:</h2>

      <ul>
        <% cine.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :phone %>
    <%= form.number_field :phone, class: "form-control" %>
  </div>
<div class="form-group">
<%= form.label :picture %>
<%= form.file_field :picture %>
</div>
  <div class="actions">
    <%= form.submit "Guardar cine", class: "btn btn-dark mt-3 btn-block" %>
  </div>
<% end %>

app/views/cines/edit.html.erb
<div class="row justify-content-center ">
<div class="col-sm-12 col-xl-6 col-md-12 col-12">
<div class="card">
    <div class="card-body">
<h1 class="card-header text-center mb-5" >Editar cine</h1>
<%= image_tag @cine.picture.thumb.url, class: "figure-img img-fluid img-thumbnail rounded mb-3" %>
<%= render "form", cine: @cine %>
<div class="col text-center">
<%= link_to "Show", @cine, class: "btn btn-outline-dark mt-3" %> 
<%= link_to "Back", cines_path, class: "btn btn-outline-dark mr-2 mt-3 " %>
</div>
</div>
</div>
</div>
</div>

app/views/cines/index.html.erb
<div class="row justify-content-center ">
<div class="col-sm-12 col-xl-6 col-md-12 col-12">
<p id="notice"><%= notice %></p>

<h1 class="text-center mb-3">Sección de los cines </h1>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th>Nombre</th>
      <th>Telefono</th>
      <th>Portada</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cines.each do |cine| %>
      <tr>
        <td><%= cine.name %></td>
        <td><%= cine.phone %></td>
        <td><%= image_tag cine.picture.thumb.url, class: "figure-img img-fluid img-thumbnail rounded" %></td>
        <td><%= link_to "Ver", cine, class: "btn btn-light far fa-eye" %></td>
        <td><%= link_to "Editar", edit_cine_path(cine), class: "btn btn-light far fa-edit" %></td>
        <td><%= link_to "Eliminar", cine, method: :delete, data: { confirm: "¿Esta seguro?" }, class: "btn btn-light far fa-trash-alt " %></td></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div class="col text-center">
<%= link_to "Agregar cine", new_cine_path, class: "btn-centro btn btn-dark" %>
</div>
</div>
</div>

app/views/cines/new.html.erb
<div class="row justify-content-center ml-5">
<div class="col-sm-12 col-xl-6 col-md-12">
    <div class="card">
    <div class="card-body">
<h1 class="card-header text-center mb-3" >Nuevo cine</h1>

<%= render "form", cine: @cine %>

<%= link_to "Back", cines_path, class: "btn btn-outline-dark  " %>
</div>
</div>
</div>
</div>

app/views/cines/show.html.erb
<div class="row justify-content-center ml-5 ">
<div class="col-sm-12 col-xl-6 col-md-12">
<div class="card">
<div class="card-body show">
<p id="notice"><%= notice %></p>
<%= image_tag @cine.picture.thumb.url, class: "figure-img img-fluid img-thumbnail rounded mb-3" %>
<p>
<p>
  <strong>Nombre:</strong>
  <%= @cine.name %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @cine.phone %>
</p>

<%= link_to "Edit", edit_cine_path(@cine), class: "btn btn-dark " %> 
<%= link_to "Back", cines_path, class: "btn btn-outline-dark ml-3" %>
</div>
</div>
</div>
</div>

app/views/home/index.html.erb
 <div class="row justify-content-center ">
<div class="col-sm-12 col-xl-9 col-md-12 col-12">
<p id="notice"><%= notice %></p>

<h1 class="text-center mt-5 ">C A R T E L E R A</h1>
<hr class="mb-5">
<div class="row text-center">
<% @movies.each do |movie| %>
      <div class="col-lg-3 col-md-6 mb-4">
        <div class="card h-100">
          <%= image_tag movie.picture.thumb.url, class: "figure-img img-fluid img-thumbnail rounded" %>
          <div class="card-body">
            <h4 class="card-title"><%= movie.name %></h4>
            <p class="card-text"><strong>Estreno: <%= movie.date_time_movie.strftime("%F") %></strong> </p>
            <p class="card-text"><strong>Hora: <%= movie.date_time_movie.strftime("%H:%M") %></strong> </p>
            <p class="card-p card-text">Duracion: <%= movie.duration.strftime("%H:%M") %></p>
            <p class="card-cine card-text">Cine: <%= movie.cine.name %></p>  
          </div>
        </div>
      </div>
      <% end %>
    </div>

</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cinema</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
    <%= javascript_pack_tag "application", 'data-turbolinks-track': "reload" %>
   <link
      rel="icon"
      type="image/png"
      sizes="35x35"
      href="https://i.ibb.co/M8HZpKt/icons8-cinema-25px.png"
    />
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
<script src="https://kit.fontawesome.com/5e07bc66cd.js" crossorigin="anonymous"></script>
  </head>
  <body>
<nav class="navbar navbar-dark bg-dark navbar-expand-lg navbar-toggler-md sticky-top">
  <a class="navbar-brand" href="<%= home_index_path %>">CINEMA</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav mr-auto ml-5">
      <li class="nav-item">
        <a class="nav-link" href="<%= home_index_path %>">CARTELERA</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Admin
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="<%= cines_path %>">Cines</a>
          <a class="dropdown-item" href="<%= movies_path %>">Peliculas</a>
        </div>
      </li>
   </ul>
  
     <ul class="navbar-nav" >
     <li class="nav-item">
     <% if user_signed_in? %>
      <a class="nav-link" href="<%= destroy_user_session_path %>" data-method="delete"><%= current_user.email %></a>
     <% else %>
     <a class="nav-link" href="<%= new_user_session_path %>"> Iniciar sesión</a>
     <% end %>  
     </li>
     </ul>
  </div>
</nav>
  <div
    id="carousel"
    class="carousel slide"
    data-ride="carousel"
    data-interval="6500"
  >
    <div class="carousel-inner">
      <div class="carousel-item active">
        <%= image_tag("https://images.pexels.com/photos/436413/pexels-photo-436413.jpeg", :alt => "rss feed", :class => "w-100") %>
        <div class="carousel-caption">
        </div>
      </div>

      <div class="carousel-item">
         <%= image_tag("https://images.pexels.com/photos/4061506/pexels-photo-4061506.jpeg", :alt => "rss feed", :class => "w-100") %>
      </div>

      <div class="carousel-item">
         <%= image_tag("https://images.pexels.com/photos/33129/popcorn-movie-party-entertainment.jpg", :alt => "rss feed", :class => "w-100") %>
      </div>
    </div>

    <ol class="carousel-indicators">
      <li data-target="#carousel" data-slide-to="0" class="active"></li>
      <li data-target="#carousel" data-slide-to="1"></li>
      <li data-target="#carousel" data-slide-to="2"></li>
    </ol>
  </div>

    <div class="container">
    <div>
    <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
      <%= yield %>
   </div>
    <div class="social mt-5">
      <a href="https://www.facebook.com/" target="_blank"><i class="fab fa-facebook"></i></a>
      <a href="https://twitter.com/" target="_blank"><i class="fab fa-twitter"></i></a>
      <a href="https://myaccount.google.com/"target="_blank"><i class="fab fa-google-plus-g"></i></a>
      <a href="https://www.instagram.com/" target="_blank"><i class="fab fa-instagram"></i></a>
      <a href="https://www.youtube.com/" target="_blank"><i class="fab fa-youtube"></i></a>
    </div>
   <footer class="bg-dark ">
<div class="container">
<div class="row justify-content-center text-center text-light">
    <div class="col-md-9">
        
        <p class="pt-3">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's</p>
    </div>
    <div class="col-md-4">
        <hr class="bg-light">
        <h5>Contacto</h5>
        <hr class="bg-light">
        <h5>2222-2222</h5>
        <p>email@cinema.com</p>
        <p>100 Managua</p>
        <p>Nicaragua</p>
    </div>
    <div class="col-md-4">
        <hr class="bg-light">
        <h5>Horario</h5>
        <hr class="bg-light">
        <p>Monday: 9am - 5pm</p>
        <p>Sabados: 11am - 5pm</p>
        <p>Domingos: 12pm - 5pm</p>
    </div>
    <div class="col-md-4">
        <hr class="bg-light">
        <h5>Area Servicio</h5>
        <hr class="bg-light">
        <p>Managua, 000000</p>
        <p>Chinandega, 000000</p>
        <p>Esteli, 000000</p>
        <p>Leon, 000000</p>
        <p>Masaya, 000000</p>
    </div>
</div>
</div>

</footer>

<div class="bg-dark socket text-light text-center py-4">
    <p>&copy; <a href=""></a>Cinema Nicaragua</p>
</div>

  </body>
</html>

app/views/movies/_form.html.erb
<%= form_with(model: movie, local: true) do |form| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> Prohibió que se guardara esta película</h2>

      <ul>
        <% movie.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>
 <div class="form-group">
    <%= form.label :picture %>
    <%= form.file_field :picture %>
  </div>
  <div class="form-group">
    <%= form.label :duration %>
    <%= form.time_select :duration, class: "form-control" %>
  </div>

  <div class="form-group">
  <%= form.label :cine_id %>
  <%= select("movie", "cine_id", @cine, { include_blank: true }, class: "form-control") %>
  </div>
  <div class="form-group">
    <%= form.label :date_time_movie %>
    <%= form.datetime_select :date_time_movie %>
  </div>

  <div class="actions">
    <%= form.submit "Guardar Pelicula", class: "btn btn-dark btn-block" %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<div class="row justify-content-center ml-5">
<div class="col-sm-12 col-xl-6 col-md-12">
    <div class="card">
    <div class="card-body">
    <h1 class="card-header text-center mb-3">Editar Pelicula</h1>
<%= image_tag @movie.picture.thumb.url, class: " img-thumbnail rounded mb-3" %>
<%= render "form", movie: @movie %>
<div class="col text-center">
<%= link_to "Show", @movie, class: "btn btn-outline-dark mt-3 " %> 
<%= link_to "Back", movies_path, class: "btn btn-outline-dark mr-2 mt-3" %>
</div>
</div>
</div>
</div>
</div>

app/views/movies/index.html.erb
<div class="row justify-content-center ">
<div class="col-sm-12 col-xl-9 col-md-12 col-12">
<p id="notice"><%= notice %></p>

<h1 class="text-center mb-3">Sección de peliculas</h1>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th>Nombre</th>
      <th>Duracion</th>
      <th>Fecha Estreno</th>
      <th>Imagen</th>
      <th>Cine</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.name %></td>
        <td><%= movie.duration.strftime("%H:%M") %></td>
        <td><%= movie.date_time_movie.strftime("%F  Hora: %H:%M") %></td>
        <td><%= image_tag movie.picture.thumb.url, class: "figure-img img-fluid img-thumbnail rounded" %></td>
       <td><%= movie.cine.name %></td>
        <td><%= link_to "Ver", movie, class: " btn btn-light far fa-eye " %></td>
        <td><%= link_to "Editar", edit_movie_path(movie), class: "btn btn-light far fa-edit" %></td>
        <td><%= link_to "Eliminar", movie, method: :delete, data: { confirm: "¿Esta seguro?" }, class: "btn btn-light far fa-trash-alt " %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="col text-center">
<%= link_to "Agregar pelicula", new_movie_path, class: "btn-centro btn btn-dark" %>
</div>
</div>
</div>

app/views/movies/new.html.erb
<div class="row justify-content-center ml-5">
<div class="col-sm-12 col-xl-6 col-md-12">
    <div class="card">
    <div class="card-body">
<h1 class="card-header text-center mb-3" >Nueva Pelicula</h1>

<%= render "form", movie: @movie %>

<%= link_to "Back", movies_path, class: "btn btn-outline-dark  " %>
</div>
</div>
</div>
</div>

app/views/movies/show.html.erb
<div class="row justify-content-center ml-5 ">
<div class="col-sm-12 col-xl-6 col-md-12">
<div class="card">
<div class="card-body show">
<p id="notice"><%= notice %></p>

<%= image_tag @movie.picture.thumb.url, class: " img-thumbnail rounded mb-3" %>
<p>
  <strong>Nombre:</strong>
  <%= @movie.name %>
</p>
<p>
  <strong>Cine:</strong>
  <%= @movie.cine.name %>
</p>
<p>
  <strong>Duracion:</strong>
  <%= @movie.duration.strftime("%H:%M") %>
</p>

<p>
  <strong>Fecha de estreno:</strong>
  <%= @movie.date_time_movie.strftime("%F") %>
</p>
<p>
  <strong>Hora:</strong>
  <%= @movie.date_time_movie.strftime("%H:%M") %>
</p>


<%= link_to "Edit", edit_movie_path(@movie), class: "btn btn-dark " %> 
<%= link_to "Back", movies_path, class: "btn btn-outline-dark ml-3" %>
</div>
</div>
</div>
</div>